### ISSUE TITLE
Necessity of the scale parameter?

### ISSUE THREAD

**Issue by KindXiaoming** [Blealtan/efficient-kan#1]
Hi, I just want to share my experience when I developed KAN that the scale parameter seems quite important (but that was in the very beginning of the KAN project, so I could be hallucinating). Would love to hear your experimental results! Great initiative, would love to see a more efficient KAN implementation (with good features maintained).

**Comment by Blealtan** [comment]
Thank you for your information. It's added back now with a controlling option, but I haven't yet done any experiments on that.

**Comment by KindXiaoming** [comment]
[heart]         Ziming Liu reacted to your message:
________________________________
