### ISSUE TITLE
please report a bug to PyTorch. torch.linalg.lstsq: (Batch element 0): Argument 6 has illegal value. Most certainly there is a bug in the implementation calling the backend library.

### ISSUE THREAD

**Issue by maomaocun** [Blealtan/efficient-kan#25]
File "tests/test_simple_math.py", line 166, in curve2coeff
    solution = torch.linalg.lstsq(   # 使用最小二乘法求解线性方程组
RuntimeError: false INTERNAL ASSERT FAILED at "../aten/src/ATen/native/BatchLinearAlgebra.cpp":1462, please report a bug to PyTorch. torch.linalg.lstsq: (Batch element 0): Argument 6 has illegal value. Most certainly there is a bug in the implementation calling the backend library.

What happened？
![image](https://github.com/Blealtan/efficient-kan/assets/124250220/8efb2237-dd2b-43fd-b6f0-0f97721538f9)

**Comment by Blealtan** [comment]
See #4.
