### ISSUE TITLE
Train Multi-KANs simultaneously! Coding realization

### ISSUE THREAD

**Issue by dwtum** [Blealtan/efficient-kan#30]
Hey, guys. Now I have this problem, the structure is like following:

y_pred = KAN_1(X1)*f1(X1) + KAN_2(X2)*f2(X2) + KAN_3(X3)*f3(X3),f1,f2,f3 is all fixed and known functions, how can I train KAN_i，i=1,2,3 simultaneously? 

I am wondering how can I realize this training process.

**Comment by UnbearableFate** [comment]
maybe you can use torch.distributed to train your different models in the multiprocess, and allreduce the results

**Comment by dwtum** [comment]
#mlp is MLP class defined with torch.nn
mlp_p1 = mlp().to(device)
mlp_p2 = mlp().to(device)
mlp_p3 = mlp().to(device)

optimizer = torch.optim.Adam([
    {'params': mlp_p1.parameters()},
    {'params': mlp_p2.parameters()},
    {'params': mlp_p3.parameters()}
], lr=learning_rate)
    
for epoch in range(epochs):
    epoch_loss = 0.0
    p1s = mlp_p1(inputs)
    p2s = mlp_p2(inputs)
    p3s = mlp_p3(inputs)
    y_pred = p1s*p1_coefs + p2s*p2_coefs + p3s*p3_coefs  
    total_loss = CAL_loss(y_true,y_pred)
    optimizer.zero_grad()
    total_loss.backward()
    optimizer.step()
This is how I do this task with MLPs. How shall I modify it to use KAN substitute mlps?
