### ISSUE TITLE
How to pip install?

### ISSUE THREAD

**Issue by piwawa** [Blealtan/efficient-kan#40]
```cmd
$pip install efficient-kan
ERROR: Could not find a version that satisfies the requirement efficient-kan (from versions: none)
ERROR: No matching distribution found for efficient-kan
```

**Comment by Paulo-21** [comment]
try pip  install from a github repo

**Comment by gguzzy** [comment]
You can try by cloning the repo inside your working directory, using `git clone https://github.com/Blealtan/efficient-kan.git`, then you can simply run `pip install -e .` to save it in your current environment.

**Comment by JacksonBurns** [comment]
Let `pip` do the clone for you: `pip install git+https://github.com/Blealtan/efficient-kan.git`
